/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Multi-namespace decision engine.
 *
 * One `Engine` per application. Call `engine.namespace(id)` to get a
 * `Namespace` handle and operate on intents within it.
 */
export declare class Engine {
  /**
   * Create a new Engine.
   *
   * ```js
   * // in-memory
   * const engine = new Engine();
   *
   * // persistent
   * const engine = new Engine({ dataDir: '/tmp/mr' });
   *
   * // connected
   * const engine = new Engine({
   *   serverUrl: 'http://localhost:3001',
   *   apiKey: 'mr_xxx',
   *   subscribe: ['security', 'intent'],
   * });
   * ```
   */
  constructor(options?: EngineOptions | undefined | null)
  /**
   * Get a `Namespace` handle for the given id.
   * The namespace is created lazily on first write.
   */
  namespace(id: string): Namespace
  /** All namespace IDs currently loaded in this engine. */
  namespaces(): Array<string>
  /** Flush all dirty namespaces to disk (no-op if no `dataDir` was set). */
  flush(): void
}

/**
 * Handle for one namespace inside an `Engine`.
 *
 * All operations on intents and phrases go through this object.
 */
export declare class Namespace {
  /**
   * Add an intent with seed phrases (English by default).
   *
   * ```js
   * // monolingual
   * ns.addIntent('greet', ['hello', 'hi', 'hey']);
   *
   * // multilingual
   * ns.addIntent('greet', { en: ['hello'], fr: ['bonjour'] });
   * ```
   */
  addIntent(id: string, seeds: Array<string> | Record<string, Array<string>>): number
  /** Resolve a query. Returns matches sorted by score descending. */
  resolve(query: string): Array<Match>
  /** Correct a mis-classification: nudge the engine from `wrong` toward `right`. */
  correct(query: string, wrong: string, right: string): void
  /** Remove an intent and all its phrases. */
  removeIntent(id: string): void
  /** All intent IDs in this namespace. */
  intentIds(): Array<string>
  /** Number of intents in this namespace. */
  intentCount(): number
  /** Monotonic version counter; increments on every mutation. */
  version(): number
  /** Resolve with explicit threshold and gap overrides. */
  resolveWith(query: string, threshold?: number | undefined | null, gap?: number | undefined | null): Array<Match>
  /** Read-only view of an intent's metadata. Returns `null` if not found. */
  intent(intentId: string): IntentInfo | null
  /**
   * Update metadata fields on an existing intent.
   *
   * Raises an error if the intent does not exist or `intentType` is invalid.
   */
  updateIntent(intentId: string, edit: IntentEditOptions): void
  /** Add a single phrase to an existing intent. */
  addPhrase(intentId: string, phrase: string, lang?: string | undefined | null): PhraseResult
  /** Flush this namespace to disk (no-op if `Engine` has no `dataDir`). */
  flush(): void
}

/** Options for `new Engine(options)`. */
export interface EngineOptions {
  /**
   * Path to persist namespace data. Each namespace is a sub-directory.
   * Omit for in-memory only.
   */
  dataDir?: string
  /** Server URL for connected mode, e.g. "http://localhost:3001". */
  serverUrl?: string
  /** API key for the server (required when auth is enabled). */
  apiKey?: string
  /** Namespace IDs to subscribe to from the server. */
  subscribe?: Array<string>
  /** Background sync interval in seconds. Default: 30. */
  tickIntervalSecs?: number
}

/** Edit object accepted by `updateIntent`. */
export interface IntentEditOptions {
  /** `"action"` or `"context"`. */
  intentType?: string
  description?: string
  instructions?: string
  persona?: string
  guardrails?: Array<string>
}

/** Read-only view of an intent's metadata and training phrases. */
export interface IntentInfo {
  id: string
  /** `"action"` or `"context"`. */
  intentType: string
  description: string
  /** Training phrases grouped by language code. */
  training: Record<string, Array<string>>
}

/** A classification match: intent id + score. */
export interface Match {
  id: string
  score: number
}

/** Result from `addPhrase`. */
export interface PhraseResult {
  added: boolean
  redundant: boolean
  warning?: string
}
