/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Router {
  constructor()
  /** Add an intent with seed phrases. */
  addIntent(id: string, seeds: Array<string>): void
  /** Route a query — returns array of {id, score}. */
  route(query: string): Array<RouteResult>
  /** Route with multi-intent detection. */
  routeMulti(query: string, threshold?: number | undefined | null): MultiRouteOutput
  /** Learn a new paraphrase for an intent. */
  learn(query: string, intentId: string): void
  /** Correct a misroute. */
  correct(query: string, wrongIntent: string, correctIntent: string): void
  /** Set intent type: "action" or "context". */
  setIntentType(intentId: string, intentType: string): void
  /** Export router state as JSON string. */
  exportJson(): string
  /** Import router state from JSON string. */
  static importJson(json: string): Router
  /** Delete an intent. */
  deleteIntent(id: string): void
  /** List all intent IDs. */
  intentIds(): Array<string>
  /** Begin batch mode. */
  beginBatch(): void
  /** End batch mode. */
  endBatch(): void
  /** Discover intent clusters from unlabeled queries. */
  static discover(queries: Array<string>, expectedIntents?: number | undefined | null): Array<DiscoveredCluster>
}

export interface DiscoveredCluster {
  name: string
  size: number
  confidence: number
  topTerms: Array<string>
  representativeQueries: Array<string>
}

export interface MultiRouteOutput {
  confirmed: Array<MultiRouteResult>
}

export interface MultiRouteResult {
  id: string
  score: number
  intentType: string
}

export interface RouteResult {
  id: string
  score: number
}
