/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Router {
  constructor()
  /** Add an intent with seed phrases. */
  addIntent(id: string, seeds: Array<string>): void
  /** Store that query maps to intentId (phrase stored for bootstrap). */
  learn(query: string, intentId: string): void
  /** Move query from wrongIntent to correctIntent. */
  correct(query: string, wrongIntent: string, correctIntent: string): void
  /** Set intent type: "action" or "context". */
  setIntentType(intentId: string, intentType: string): void
  /** Export router state as JSON string. */
  exportJson(): string
  /** Import router state from JSON string. */
  static importJson(json: string): Router
  /** Add a seed with duplicate checking. */
  addSeed(intentId: string, seed: string, lang?: string | undefined | null): SeedResult
  /** Remove a seed from an intent. */
  removeSeed(intentId: string, seed: string): boolean
  /** Set intent description. */
  setDescription(intentId: string, description: string): void
  /** Get intent description. */
  getDescription(intentId: string): string
  /** Delete an intent. */
  deleteIntent(id: string): void
  /** List all intent IDs. */
  intentIds(): Array<string>
  /** Begin batch mode (no-op). */
  beginBatch(): void
  /** End batch mode (no-op). */
  endBatch(): void
  /** Discover intent clusters from unlabeled queries. */
  static discover(queries: Array<string>, expectedIntents?: number | undefined | null): Array<DiscoveredCluster>
}

export interface DiscoveredCluster {
  name: string
  size: number
  confidence: number
  topTerms: Array<string>
  representativeQueries: Array<string>
}

export interface SeedResult {
  added: boolean
  newTerms: Array<string>
  redundant: boolean
  warning?: string | null
}
